name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the Kopexa CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.KOPEXA_CLOUD_REPO_ACCESS_TOKEN }}
        with:
          path-to-signatures: "signatures/version1/cla.json"
          path-to-document: "https://github.com/kopexa-grc/.github/blob/main/CLA.md"
          custom-pr-sign-comment: "I have read the Kopexa CLA Document and I hereby sign the CLA"
          custom-notsigned-prcomment: "Thank you for your submission. We really appreciate it. Before we can accept your contribution, we ask that you sign the [Kopexa Contributor License Agreement](https://github.com/kopexa-grc/.github/blob/main/CLA.md). You can sign the CLA by adding a new comment to this pull request and pasting exactly the following text."
          remote-repository-name: cla
          remote-organization-name: kopexa-grc
          branch: "main"
          allowlist: kopexa-tools,github-actions[bot],dependabot[bot]