name: Code Quality

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/code-quality.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/code-quality.yml'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  goreportcard:
    name: Go Report Card
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Go Report Card
        uses: creekorful/goreportcard-action@v1.0

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Run Tests with Coverage
        run: go test -coverprofile=coverage.out ./...

    #   - name: SonarCloud Scan
    #     uses: SonarSource/sonarcloud-github-action@master
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     with:
    #       args: >
    #         -Dsonar.projectKey=kopexa-grc_notifier
    #         -Dsonar.organization=kopexa-grc
    #         -Dsonar.go.coverage.reportPaths=coverage.out 